### ISSUE TITLE
Broken internal links on Jargon Buster

### ISSUE THREAD

**Issue by IanDitchfield2** [jpickup/mvoc-iconic-one-theme#15]
I've been running Xenu (see Jargon Buster!) on the new site.  A lot of dross in the report, and I'm trying to work out what matters and what doesn't. However one section of the report is clear, indicating some broken internal links within the new Jargon Buster
![Screenshot 2024-06-11 at 12 01 33](https://github.com/jpickup/mvoc-iconic-one-theme/assets/171923548/38083eb0-bb69-4163-b5fa-d9a17c0e0eea)

**Comment by jpickup** [comment]
The jargon buster items are fixed now. The first two missing items must have been accidents when Tim removed the first item under a letter as those had the anchors.
