### ISSUE TITLE
Broken link report 12 June

### ISSUE THREAD

**Issue by IanDitchfield2** [jpickup/mvoc-iconic-one-theme#19]
As you will see, I'm still tinkering with the Xenu exclusions list to try and get rid of dross without missing anything important. Not quite right yet, ignore the 'error code 204's on this list. 

Also ignore the the '403 (forbidden request)'s; they seem to indicate something Xenu doesn't like about the page being linked to, but web browsers seem to cope OK.

The remaining items on the '404 (not found)' list look like they do need attention. 

For this run, I've also tried to exclude links to the old website, so that we can concentrate on the new website first. When you get down to the redirections list, you'll see that I haven't completely succeeded. The vast bulk of the redirections should be ignored. I'm hoping that if you can progress issue 16, that will get rid of most of them. I'm ignoring them all for the moment.

[Xenu report 12 June.pdf](https://github.com/user-attachments/files/15800837/Xenu.report.12.June.pdf)

**Comment by jpickup** [comment]
I think I've fixed the majority of the problems. Done far too much messing about to have an easy way to see what I've missed.  There were a few that I've definitely not fixed as they are generated rahter than embedded in page/post content.

Have also updated the links on the old website to consistently use archive so that should now be OK too.

It's entirely possible I've created some new issues.

Please could you run the scan again?

**Comment by IanDitchfield2** [comment]
Run again.
[Xenu run 2.pdf](https://github.com/user-attachments/files/15812058/Xenu.run.2.pdf)

**Comment by jpickup** [comment]
OK. The majority of those are now fixed. Well, at least the ones that matter. 

I don't understand a few of them, like the BOK links as they do work so the 403 must be the site rejecting a request from Xenu or something.

The broken links related to navigation on the events pages I doubt I'll be able to solve.

Annoyingly the pdf didn't allow me to either click on URLs or copy/paste them. Tried three different viewers!

**Comment by IanDitchfield2** [comment]
The PDF arises because I'm running Xenu on a Windows emulator, and then trying to transfer the output to the main part of my Mac. The original output is a webpage, which I "print" as a pdf, then save that pdf on the shared drive.
Then back on the Mac, I post the pdf from the shared drive to GitHub.
I've just kicked off another run of Xenu; this time I'll see if I can post to GitHub from the emulator. Although doing anything on the emulator is very clunky, and I can't get key shortcuts like copy and paste to work.
Watch this space....

**Comment by jpickup** [comment]
What are you using for Windows emulation? I've only ever used VMs like Parallels and Virtual Box rather than emulators. The latter is free and works pretty well, even on my 11 year old iMac. I've used it for Purple Pen and Xenu plus for testing of software that I've written that Windows folks want to use.

**Comment by IanDitchfield2** [comment]
Virtual Box. Is emulator the wrong term for it? It creates a Windows partition that gobbles up almost all the resource on my Mac while it's open. And yes, it works pretty well, albeit slowly.

**Comment by IanDitchfield2** [comment]
Incidentally, nothing to stop you cutting me out and running Xenu yourself. Free software, link from the Jargon Buster :)

**Comment by IanDitchfield2** [comment]
Finally!
If only I could find a way of copying text (cmd/C on the Mac) which work in Virtual Box, I could save at least an hour - Microsoft print to pdf moves all the speed of an arthritic snail.
[Xenu report 13 June.pdf](https://github.com/user-attachments/files/15817302/Xenu.report.13.June.pdf)

**Comment by jpickup** [comment]
That's much cleaner. I've fixed the typo on the Mole Roll. 

By emulator I thought you meant something like WINE, which allows Windows apps to run under Linux, and which can be flaky. Interestingly the name means "Wine is not an emulator" so my mental association is completely wrong! VMs are indeed emulators but for some reason they are always referred to as VMs so I don't naturally associate emulator with them. 

Have you tried installing the Virtual Box Guest Extensions into your Windows VM? This gives clipboard integration amongst other things.

**Comment by IanDitchfield2** [comment]
I think I do have Guest Extensions installed.  

The problem is not so much sharing the clipboard, as finding a way to get stuff onto the clipboard. I simply cannot find a way to copy-to-clipboard. It's probably there somewhere, but so basic that nobody seems to document how to do it. It certainly isn't the cmd-c that works on the Mac side.

I probably ought to https://mvoc.org/archive for the next run.  Last time I tried that, it produced a report so big that I couldn't save it! But I think I, and probably you too, need a break first.

**Comment by jpickup** [comment]
I just tried Ctrl-A, Ctrl-C in the Guest (Windows) OS and it copied the whole report from Xenu into the clipboard. Cmd-V on the Mac then pastes it. I'm running Virtual Box 7.0 if that's relevant.

**Comment by jpickup** [comment]
I've run the report for the archive and, errr, got loads of timeouts. 
Dialed Xenu down to a single thread and that kind of helps, except after it scanned a few hundred pages I start getting forbidden request and 429 errors. Looks like Xenu is annoying the server with the number of calls. Somehow need to throttle the calls and leave it for a longer time.

**Comment by IanDitchfield2** [comment]
When it finishes and asks whether you want a report, I usually say "no", and follow with "retry broken links" from the "file" dropdown. Repeat until the number of urls inspected (on the bottom bar of the panel) is unchanged since last time, and only then say "yes" to the report.

**Comment by IanDitchfield2** [comment]
Ran report again. Not much on it. Some I've fixed. Some 403's on external sites which I know to ignore.

And some items which I don't understand; if they're definitely not a problem I can exclude them from future runs. But maybe they are a problem. Any ideas?

Broken links, ordered by page:

https://mvoc.org/index.php/events/
	https://mvoc.org/events/list/?pagename=events&eventDisplay=past
	  \_____ error code: 404 (not found)
	https://mvoc.org/events/list/?pagename=events
	  \_____ error code: 404 (not found)

https://mvoc.org/index.php/events/featured/
	https://mvoc.org/events/list/featured/?pagename=events%2Ffeatured&eventDisplay=past
	  \_____ error code: 404 (not found)
	https://mvoc.org/events/list/featured/?pagename=events%2Ffeatured
	  \_____ error code: 404 (not found)

https://mvoc.org/index.php/page/2/?post_type=tribe_events&eventDisplay=day
	https://mvoc.org/index.php/page/2/?post_type=tribe_events&eventDisplay=day&ical=1
	  \_____ error code: 204 (no info to return)

**Comment by jpickup** [comment]
This is odd. I don't understand it. Taking this broken link:
https://mvoc.org/events/list/?pagename=events&eventDisplay=past
it doesn't work so the tool is correct. I just don't know where it's finding it as the Prev button results in this URL that is valid:
https://mvoc.org/events/list/?eventDisplay=past

Finding bad links on a site that's generated by code is going to be tricky.

**Comment by IanDitchfield2** [comment]
I’m happy to ignore ‘system generated’ missing links unless and until people actually find a missing link when using the website.
Running Xenu was useful for me as it found a couple of errors in the events I’d set up.
Think we can close this one now?

**Comment by jpickup** [comment]
OK. Let's close for now. Thanks.
