### ISSUE TITLE
Day of week in details?

### ISSUE THREAD

**Issue by IanDitchfield2** [jpickup/mvoc-iconic-one-theme#23]
On our event details pages, could we display the weekday?

Thus
DETAILS
Date:
Thursday 20 June 2024

rather than
DETAILS
Date:
20 June 2024

**Comment by jpickup** [comment]
Fortunately that's part of the events plug-in config, which I've changed.

**Comment by IanDitchfield2** [comment]
Thanks.
Other considerations apart, it's helpful for me checking that I've got the date right when setting up a new event - when viewing event after creating it, a wrong day of the week jumps out much more than a wrong year, or today's date (both of which are easy mistakes to make).
