### ISSUE TITLE
Icons on the Events Calendar list pages

### ISSUE THREAD

**Issue by IanDitchfield2** [jpickup/mvoc-iconic-one-theme#25]
On the detail page for an event, there are a whole load of icons that can appear.
On the events listing page, where there are up to 50(?) events, icons also appear for each event, but fewer of them. Is there any reason why they shouldn't all appear? I was particularly noticing that the Streetmap icon never seems to appear on listings, but there other differences too.

**Comment by jpickup** [comment]
I'd not added StreetMap and W3W icons to the list style, only Google Maps. I've added them now. One impact is the use of more space so we have wrapping of the description. Worth it? What do you think?

**Comment by IanDitchfield2** [comment]
I don't think I'm seeing any extra wrapping, either on laptop or mobile. Looks OK to me.

**Comment by jpickup** [comment]
OK. I've committed that change now.
