### ISSUE TITLE
SEOUL not SEUOL

### ISSUE THREAD

**Issue by IanDitchfield2** [jpickup/mvoc-iconic-one-theme#26]
Very low importance, but I've noticed that in the results area we have SEUOL rather that the correct SEOUL. (This is Southern England Orienteering Urban League; I do agree that SEUOL would be a more natural word ordering, but that's not what the person who originally set up the league chose). I've noticed this while looking at the Reigate 29/8/23 results, but it may be elsewhere too.

**Comment by jpickup** [comment]
That should be fixed now.

**Comment by IanDitchfield2** [comment]
That was quick!
