### ISSUE TITLE
Map icons on event detail pages

### ISSUE THREAD

**Issue by IanDitchfield2** [jpickup/mvoc-iconic-one-theme#27]
Very minor quibble, but (when present at all) the icons for W3W and Streetmap (but not Google maps) are appearing twice on the event detail pages.
![Screenshot 2024-07-04 at 12 00 25](https://github.com/jpickup/mvoc-iconic-one-theme/assets/171923548/48f606fe-c920-439b-9baa-c881179d0477)

**Comment by jpickup** [comment]
Fixed. That was due to me adding all map icons to code shared by both the listing page events details but not removing what were previously extras from the details page.
