### ISSUE TITLE
Events time setup seems to have changed

### ISSUE THREAD

**Issue by IanDitchfield2** [jpickup/mvoc-iconic-one-theme#28]
Two changes, neither for the better from my perspective.

1) the time now defaults to 08:00-17:00 instead of all-day. 
It seemed fairly intuitive to me that 'all-day' implied that no time had been specified, and was OK for any event, where as 8am-5pm is clearly nonsense for many events (especially night events!).

2) the option to set an automatic deletion, which I routinely use to delete non-Mole events a week after they have happened, has disappeared.

(and it is possible to edit the content too - look at the ... button on the top-right)

**Comment by IanDitchfield2** [comment]
Please ignore the second point - I've managed to get the automatic deletion option back.  The point about the default time still applies.

(and why does GitHub let me edit the title, but not the content!?)

**Comment by jpickup** [comment]
The calendar plug-in updates happen appreoximately weekly so the change in the default value for the "All Day Event" checkbox may have changed in a recent update. It's a difference of one click so I don't think I can complain.

**Comment by IanDitchfield2** [comment]
It's not so much the extra effort of the one click if I remember, more that the we get an event created with incorrect information if I don't remember. However, it's not a big deal and I agree not worth making a fuss over.
