### ISSUE TITLE
Kent Night Cup

### ISSUE THREAD

**Issue by IanDitchfield2** [jpickup/mvoc-iconic-one-theme#29]
On the Events Calendar, could you please add a "series" for the Kent Night Cup, abbreviation KNC, link to https://www.saxons-oc.org/info/kent-night-cup

**Comment by jpickup** [comment]
That's added now:
![image](https://github.com/user-attachments/assets/4a972e1f-2417-4548-89ac-d6ee8942ac18)
And added as a sub-menu under Events > Series

(for some reason my fingers insisted on typing "Knight" rather than "Night" but I think I've corrected that)

**Comment by jpickup** [comment]
I've just renamed the categry to KNC as I've remembered why I didn't use full names - they need to be compact otherwise take up loads of space on the event listing and look terrible.

**Comment by IanDitchfield2** [comment]
Thanks :)
