### ISSUE TITLE
Cancelled tag?

### ISSUE THREAD

**Issue by IanDitchfield2** [jpickup/mvoc-iconic-one-theme#6]
Would be nice to have a 'cancelled' tag - see White Rose 24/8/2024 for example

**Comment by IanDitchfield2** [comment]
Actually I think I'll withdraw this suggestion. I was looking at the single event view, where having typed 'Cancelled' in as a tag, it spreads over three lines.
However what people will see first is the list view, and here it write 'Cancelled' in bold. So maybe it's better without an icon?

**Comment by jpickup** [comment]
I can create an icon for cancelled, like a red cross or similar, which I think will work well. We can try it and see.

**Comment by IanDitchfield2** [comment]
Looks good. I've added text 'event cancelled' as well
